<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MassTransit" Version="9.0.0-develop.33" />
    <PackageReference Include="MassTransit.RabbitMQ" Version="9.0.0-develop.33" />
    <PackageReference Include="MessagePack" Version="3.1.4" />
    <PackageReference Include="MessagePack.Annotations" Version="3.1.4" />
    <PackageReference Include="Microsoft.Extensions.Caching.Memory" Version="10.0.1" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="10.0.1" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.1" />
	  <PackageReference Include="Microsoft.Orleans.Server" Version="8.2.0" />
	  <PackageReference Include="Microsoft.Orleans.Client" Version="8.2.0" />
	  <PackageReference Include="Microsoft.Orleans.Reminders" Version="8.2.0" />
	  <PackageReference Include="Orleans.Providers.MongoDB" Version="8.2.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Application\Application.csproj" />
    <ProjectReference Include="..\Domain\Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Shared\Contracts\Contracts.csproj" />
  </ItemGroup>

</Project>
