<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Snapshot\Chat\Dtos\" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Message\Command\BroadcastMessageCommand.cs" />
  </ItemGroup>

</Project>
