<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AspNetCoreRateLimit" Version="5.0.0" />
    <PackageReference Include="MassTransit" Version="9.0.0-develop.31" />
    <PackageReference Include="MassTransit.RabbitMQ" Version="9.0.0-develop.31" />
    <PackageReference Include="MessagePack" Version="3.1.4" />
    <PackageReference Include="MessagePack.Annotations" Version="3.1.4" />
	  <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.6" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Application\Application.csproj" />
    <ProjectReference Include="..\Domain\Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Shared\Contracts\Contracts.csproj" />
  </ItemGroup>

</Project>
