<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Domain\Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MassTransit" Version="8.5.7" />
    <PackageReference Include="MassTransit.RabbitMQ" Version="8.5.7" />
    <PackageReference Include="MediatR" Version="12.4.1" />
    <PackageReference Include="MessagePack" Version="3.1.4" />
    <PackageReference Include="MessagePack.Annotations" Version="3.1.4" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Dtos\Chat\" />
    <Folder Include="Future\Authentication\Commend\Validation\" />
    <Folder Include="Future\Snapshot\Commend\Handler\" />
    <Folder Include="Future\Snapshot\Commend\Models\" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Contracts">
      <HintPath>..\..\Shared\Contracts\bin\Debug\net9.0\Contracts.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
